matrix:
  - name: Java
    aspell:
      lang: en
    dictionary:
      encoding: utf-8
      wordlists:
        - wordlist.txt
    sources:
      - '**/*.java'
    excludes:
      - 'src/main/generated/**'
      - '**/test/**'
    default_encoding: utf-8