package com.plaything.api.common.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode implements CodeInterFace {

    SUCCESS("SUCCESS"),

    // USER 가입 or 로그인
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    USER_SAVED_FAILED("USER_SAVED_FAILED"),
    NOT_EXIST_USER("NOT_EXIST_USER"),
    MIS_MATCH_PASSWORD("MIS_MATCH_PASSWORD"),

    //JWT 토큰
    TOKEN_IS_INVALID("TOKEN_IS_INVALID"),
    ACCESS_TOKEN_IS_NOT_EXPIRED("TOKEN_IS_NOT_EXPIRED"),
    TOKEN_IS_EXPIRED("TOKEN_IS_EXPIRED"),


    //프로필 사진 업로드
    EXTENSION_IS_INVALID("EXTENSION_IS_INVALID"),
    SIZE_IS_INVALID("SIZE_IS_INVALID"),
    CONTENT_TYPE_IS_INVALID("CONTENT_TYPE_IS_INVALID"),
    IMAGE_SAVED_FAILED("IMAGE_SAVED_FAILED"),
    EXCEED_IMAGE_LIMIT("EXCEED_IMAGE_LIMIT"),
    NO_IMAGE_FAILED("NO_IMAGE_FAILED"),

    //프로필 조회 or 등록
    NOT_EXIST_PROFILE("NOT_EXIST_PROFILE"),
    PROFILE_REGISTER_FAILED("PROFILE_REGISTER_FAILED"),
    PROFILE_ALREADY_EXIST("PROFILE ALREADY EXIST"),
    NOT_EXIST_PROFILE_RECORD("NOT EXIST PROFILE RECORD"),

    //프로필 성향
    NOT_EXIST_PRIMARY_TRAIT("NOT EXIST PRIMARY TRAIT"),
    TRAITS_NOT_INCLUDE_PRIMARY("TRAITS NOT INCLUDE PRIMARY TRAIT"),
    ROLE_MISMATCH("ROLE MISMATCH"),
    NOT_EXIST_OPPOSITE_PRIMARY("NOT EXIST OPPOSITE PRIMARY"),


    //매칭
    MATCHING_FAIL_WITHOUT_IMAGE("MATCHING FAIL WITHOUT IMAGE"),
    MATCHING_FAIL_WITH_BAN_PROFILE("MATCHING_FAIL_WITH_BAN_PROFILE"),


    //광고
    AD_VIEW_TIME_NOT_EXPIRED("AD_VIEW_TIME_NOT_EXPIRED"),
    POINT_KEY_SAVED_FAILED("POINT KEY SAVED FAILED"),


    //포인트 키 사용
    NOT_EXIST_AVAILABLE_POINT_KEY("NOT EXIST AVAILABLE POINT KEY"),


    //로그
    LOG_SAVED_FAILED("LOG SAVED FAILED"),

    //알림
    NOTIFICATION_SAVED_FAILED("NOTIFICATION SAVED FAILED"),

    //메시지
    MESSAGE_CREATION_FAILED("MESSAGE CREATION FAILED"),

    //거래
    TRANSACTION_ALREADY_PROCESSED("TRANSACTION ALREADY PROCESSED"),


    //채팅방
    NOT_EXIST_CHATROOM("채팅방이 존재하지 않습니다"),
    NOT_AUTHORIZED_CHAT_ROOM_USER("채팅방에 속한 사용자가 아닙니다"),
    PARTNER_ALREADY_LEAVE("상대방이 채팅방을 떠났습니다"),
    CHAT_ROOM_IS_OVER("이미 종료된 채팅방입니다"),
    TOO_MANY_CHAT_RATE("짧은 시간에 너무 많은 채팅 메시지를 보냈습니다"),
    NOT_AUTHORIZED_SUBSCRIBE("채널 구독 권한이 없습니다"),
    NOT_AUTHORIZED_USER("메시지 발신자가 일치하지 않습니다"),
    NOT_MATCHING_PARTNER("매칭된 파트너가 아닙니다"),

    //메시지 검사
    BAD_WORDS_FILTER("금지된 단어가 포함됐습니다.");

    private final String message;
}
